#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0") [--cpu|--gpu]
Build docker images.
If the type is not specified, it will build both cpu and gpu docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    docker build -t raster-vision-tile2vec -f Dockerfile .
fi
