#!/bin/bash

set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
PROJECT_ROOT="$( cd -P "$( dirname "$SCRIPTS_DIR" )" && pwd )"
SRC="${PROJECT_ROOT}"

function usage() {
    echo -n \
         "Usage: $(basename "$0") [--cpu|--gpu]
Run console of docker image locally.
All arguments are passed to 'docker run'.
"
}

# Parse options using scheme in
# https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
# POSITIONAL=()
# while [[ $# -gt 0 ]]
# do
#     key="$1"
#     case $key in
#         --gpu)
#         USE_GPU=TRUE
#         shift # past argument
#         ;;
#         *)    # unknown option
#         POSITIONAL+=("$1") # save it in an array for later
#         shift # past argument
#         ;;
#     esac
# done
# set -- "${POSITIONAL[@]}" # restore positional parameters

# if [ "${USE_GPU}" = "TRUE" ]
# then
#     echo "USING GPU"
#     IMAGE="raster-vision-wwt-gpu";
#     RUNTIME="--runtime=nvidia"
# else
#     IMAGE="raster-vision-wwt-cpu";
# fi
IMAGE="raster-vision-tile2vec"

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    AWS="-e AWS_PROFILE=${AWS_PROFILE:-default} -v ${HOME}/.aws:/root/.aws:ro"
    TENSORBOARD="-p 6006:6006"
    RV_CONFIG="-v ${HOME}/.rastervision:/root/.rastervision:ro"

    docker run ${RUNTIME} ${NAME} --shm-size 4G --rm -it ${TENSORBOARD} ${AWS} ${RV_CONFIG} \
           -v "$SRC"/tile2vec:/opt/src/tile2vec \
           -v "$SRC"/experiments:/opt/src/expriments \
           -v "$SRC"/notebooks:/opt/notebooks \
           -v "$SRC"/data:/opt/data \
           ${IMAGE} "${@:1}"
fi
