#!/bin/bash

set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
PROJECT_ROOT="$( cd -P "$( dirname "$SCRIPTS_DIR" )" && pwd )"
SRC="${PROJECT_ROOT}"

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run console of docker image locally.
All arguments are passed to 'docker run'.
"
}

IMAGE="raster-vision-tile2vec";

# Parse options using scheme in
# https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
# POSITIONAL=()
# while [[ $# -gt 0 ]]
# do
#     key="$1"
#     case $key in
#         --gpu)
#         IMAGE="raster-vision-gpu"
#         RUNTIME="--runtime=nvidia"
#         shift # past argument
#         ;;
#         *)    # unknown option
#         POSITIONAL+=("$1") # save it in an array for later
#         shift # past argument
#         ;;
#     esac
# done
# set -- "${POSITIONAL[@]}" # restore positional parameters


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    AWS="-e AWS_PROFILE=${AWS_PROFILE:-default} -v ${HOME}/.aws:/root/.aws:ro"
    TENSORBOARD="-p 6008:6006"
    RV_CONFIG="-v ${HOME}/.rastervision:/root/.rastervision:ro"

    docker run ${RUNTIME} ${NAME} --rm -it ${TENSORBOARD} ${AWS} ${RV_CONFIG} \
           -v "$SRC"/tile2vec:/opt/src/tile2vec \
           -v "$SRC"/experiments:/opt/src/experiments \
           -v "$SRC"/examples:/opt/notebooks \
           -v "$SRC"/data:/opt/data \
           -p 8080:8080 \
           ${IMAGE} \
           jupyter notebook \
           --ip=0.0.0.0 \
           --port=8080 \
           --no-browser \
           --allow-root \
           --notebook-dir=/opt/notebooks;
fi
